name:                AOC2020
version:             0.1.0.0
license:             BSD3
author:              "Tilde Rose"
maintainer:          "t1lde@protonmail.com"
copyright:           "2020 Tilde Rose"

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -XEmptyCase
  - -XInstanceSigs
  - -XLambdaCase
  - -XMultiWayIf
  - -XNamedFieldPuns
  - -XTupleSections
  - -XBangPatterns
  - -XKindSignatures
  - -XTypeOperators
  - -XOverloadedStrings
  - -XScopedTypeVariables
  - -XTypeApplications
  - -XApplicativeDo
  - -XDeriveGeneric
  - -XDataKinds
  - -XDerivingVia
  - -XRecordWildCards
  - -XDeriveFunctor
  - -XDeriveTraversable
  - -XOverloadedLabels
  - -XFlexibleInstances
  - -XFlexibleContexts
  - -XMultiParamTypeClasses
  - -XGADTs
  - -XTypeFamilies
  - -XAllowAmbiguousTypes
  - -XConstraintKinds
  - -XStandaloneDeriving
  - -XPolyKinds
  - -XFunctionalDependencies
  - -XRankNTypes
  - -XViewPatterns
  - -XOverloadedLabels

executables:
  advent:
    main:          Runner.hs
    source-dirs:  AOC
    ghc-options:
    - -O0
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - name: base
      version: ">= 4.7 && < 5"
      mixin: &base-mixin
        - hiding (Prelude)
    - name: relude
      mixin: &relude-mixin
        - (Relude as Prelude, Relude.Extra.Foldable1, Relude.Extra.Type, Relude.Extra.Newtype, Relude.Extra.Map)
    - mtl
    - text
    - containers
    - bifunctors
    - unordered-containers
    - split
    - transformers
    - filepath
